### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [1]:
import numpy as np
a=[]
for i in range(10):
    a.append(i)
a1 = [i for i in range(10)]
b=[]
for c in "test":
    b.append(c)
b1 = [c for c in "test"]
c = []
for i in range(10):
    if i%2==0:
        c.append(i)
c1 = [i for i in range(10) if i%2==0]
a, a1, b, b1, c, c1


([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 ['t', 'e', 's', 't'],
 ['t', 'e', 's', 't'],
 [0, 2, 4, 6, 8],
 [0, 2, 4, 6, 8])

### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [10]:
v = np.array([2,3,5,7])
print('{}'.format(len(v)))
list = [value for value in range(11) if ((value == 2 or (value %2 !=0 and all(value % x !=0 for x in range(2, value//2))))and value !=1)]
v.size, v.dtype, list

4


(4, dtype('int64'), [2, 3, 5, 7])

### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [26]:
a = np.random.randint(0,20,10)
b = a[2:5]
c= np.flip(a)
c1 = a[-1::-1]
print(a/c)
lista =[]
for i in range(len(a)):
    lista.append(a[i]/c[i])
a,b,c,c1,lista


[1.4        1.         1.25       0.84615385 1.23076923 0.8125
 1.18181818 0.8        1.         0.71428571]


(array([ 7,  9, 10, 11, 16, 13, 13,  8,  9,  5], dtype=int32),
 array([10, 11, 16], dtype=int32),
 array([ 5,  9,  8, 13, 13, 16, 11, 10,  9,  7], dtype=int32),
 array([ 5,  9,  8, 13, 13, 16, 11, 10,  9,  7], dtype=int32),
 [np.float64(1.4),
  np.float64(1.0),
  np.float64(1.25),
  np.float64(0.8461538461538461),
  np.float64(1.2307692307692308),
  np.float64(0.8125),
  np.float64(1.1818181818181819),
  np.float64(0.8),
  np.float64(1.0),
  np.float64(0.7142857142857143)])